OUTPUT_FOLDER_PATH: ""
START: '2022-05-12'
DURATION: 86400
RESOLUTION: 60
SIMULATORS: 
  SIM1:
    NAME: "UMAR"
    TYPE: "FMU"
    PATH: "$DTPY$./simulators/ressources/fmu"
  SIM2:
    NAME: "PREPROCESS"
    TYPE: "FMU"
    PATH: "$DTPY$./simulators/ressources/fmu"
  SIM3:
    NAME: "DATA"
    TYPE: "TABULAR_DATA"
    PATH: "$DTPY$./simulators/ressources/data"
  SIM4:
    NAME: "NanPlaceholder"
    TYPE: "NAN_PLACEHOLDER"
    PATH: "$DTPY$./simulators/ressources/data/override_variables.json"
  SIM6:
    NAME: "P_CTRL"
    TYPE: "FMU"
    PATH: ""
    NUMBER_OF_MODELS: 5
  SIM5:
    NAME: "COLLECTOR"
    TYPE: "COLLECTOR"
    PATH: ""
  

MAPPINGS:
  MAPPING1:
    FROM: "UMAR"
    TO: "PREPROCESS"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_preprocess_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      R272_Simulated_Air_Temperature: 24.5669
      R273_Simulated_Air_Temperature: 23.1496
      R274_Simulated_Air_Temperature: 23.1496
      R275_Simulated_Air_Temperature: 21.6
      R276_Simulated_Air_Temperature: 21.6
  MAPPING2:
    FROM: "PREPROCESS"
    TO: "UMAR"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_umar_from_preprocess.json"
  MAPPING3:
    FROM: "DATA"
    TO: "PREPROCESS"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_preprocess_from_data.json"
  MAPPING4:
    FROM: "PREPROCESS"
    TO: "COLLECTOR"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_collector_from_preprocess.json"
  MAPPING5:
    FROM: "NanPlaceholder"
    TO: "PREPROCESS"
    PATH: "mapping_preprocess_from_nan.json"
  MAPPING6:
    FROM: "P_CTRL"
    FROM_INDEX: 0
    TO: "PREPROCESS"
    PATH: "mapping_preprocess_from_p_ctrl0.json"
  MAPPING7:
    FROM: "DATA"
    TO: "P_CTRL"
    TO_INDEX: 0
    PATH: "mapping_p_ctrl_from_data.json"
  MAPPING8:
    FROM: "UMAR"
    TO: "P_CTRL"
    TO_INDEX: 0
    PATH: "mapping_p_ctrl0_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      Air_T: 24.5669
  MAPPING9:
    FROM: "P_CTRL"
    FROM_INDEX: 1
    TO: "PREPROCESS"
    PATH: "mapping_preprocess_from_p_ctrl1.json"
  MAPPING10:
    FROM: "DATA"
    TO: "P_CTRL"
    TO_INDEX: 1
    PATH: "mapping_p_ctrl_from_data.json"
  MAPPING11:
    FROM: "UMAR"
    TO: "P_CTRL"
    TO_INDEX: 1
    PATH: "mapping_p_ctrl1_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      Air_T: 23.1496
  MAPPING12:
    FROM: "P_CTRL"
    FROM_INDEX: 2
    TO: "PREPROCESS"
    PATH: "mapping_preprocess_from_p_ctrl2.json"
  MAPPING13:
    FROM: "DATA"
    TO: "P_CTRL"
    TO_INDEX: 2
    PATH: "mapping_p_ctrl_from_data.json"
  MAPPING14:
    FROM: "UMAR"
    TO: "P_CTRL"
    TO_INDEX: 2
    PATH: "mapping_p_ctrl2_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      Air_T: 23.1496
  MAPPING15:
    FROM: "P_CTRL"
    FROM_INDEX: 3
    TO: "PREPROCESS"
    PATH: "mapping_preprocess_from_p_ctrl3.json"
  MAPPING16:
    FROM: "DATA"
    TO: "P_CTRL"
    TO_INDEX: 3
    PATH: "mapping_p_ctrl_from_data.json"
  MAPPING17:
    FROM: "UMAR"
    TO: "P_CTRL"
    TO_INDEX: 3
    PATH: "mapping_p_ctrl3_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      Air_T: 21.6
  MAPPING18:
    FROM: "P_CTRL"
    FROM_INDEX: 4
    TO: "PREPROCESS"
    PATH: "mapping_preprocess_from_p_ctrl4.json"
  MAPPING19:
    FROM: "DATA"
    TO: "P_CTRL"
    TO_INDEX: 4
    PATH: "mapping_p_ctrl_from_data.json"
  MAPPING20:
    FROM: "UMAR"
    TO: "P_CTRL"
    TO_INDEX: 4
    PATH: "mapping_p_ctrl4_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      Air_T: 21.6
  MAPPING21:
    FROM: "P_CTRL"
    FROM_INDEX: 0
    TO: "COLLECTOR"
    PATH: "mapping_preprocess_from_p_ctrl0.json"
  MAPPING22:
    FROM: "P_CTRL"
    FROM_INDEX: 1
    TO: "COLLECTOR"
    PATH: "mapping_preprocess_from_p_ctrl1.json"
  MAPPING23:
    FROM: "P_CTRL"
    FROM_INDEX: 2
    TO: "COLLECTOR"
    PATH: "mapping_preprocess_from_p_ctrl2.json"
  MAPPING24:
    FROM: "P_CTRL"
    FROM_INDEX: 3
    TO: "COLLECTOR"
    PATH: "mapping_preprocess_from_p_ctrl3.json"
  MAPPING25:
    FROM: "P_CTRL"
    FROM_INDEX: 4
    TO: "COLLECTOR"
    PATH: "mapping_preprocess_from_p_ctrl4.json"