OUTPUT_FOLDER_PATH: "./"
START: '2020-01-01 00:00:00'
END: 2592000
DURATION: 2592000
RESOLUTION: 60
SIMULATORS: 
  SIM1:
    NAME: "UMAR"
    TYPE: "FMU"
    PATH: "$DTPY$./simulators/ressources/fmu"
  SIM2:
    NAME: "PREPROCESS"
    TYPE: "FMU"
    PATH: "$DTPY$./simulators/ressources/fmu"
  SIM3:
    NAME: "DATA"
    TYPE: "TABULAR_DATA"
    PATH: "$DTPY$./simulators/ressources/data"
  SIM4:
    NAME: "NanPlaceholder"
    TYPE: "NAN_PLACEHOLDER"
    PATH: "$DTPY$./simulators/ressources/data/override_variables.json"
  SIM6:
    NAME: "P_CTRL"
    TYPE: "FMU"
    PATH: ""
  SIM5:
    NAME: "COLLECTOR"
    TYPE: "COLLECTOR"
    PATH: ""
  

MAPPINGS:
  MAPPING1:
    FROM: "UMAR"
    TO: "PREPROCESS"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_preprocess_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      R272_Simulated_Air_Temperature: 24.5669
      R273_Simulated_Air_Temperature: 23.1496
      R274_Simulated_Air_Temperature: 23.1496
      R275_Simulated_Air_Temperature: 21.6
      R276_Simulated_Air_Temperature: 21.6
  MAPPING2:
    FROM: "PREPROCESS"
    TO: "UMAR"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_umar_from_preprocess.json"
  MAPPING3:
    FROM: "DATA"
    TO: "PREPROCESS"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_preprocess_from_data.json"
  MAPPING4:
    FROM: "UMAR"
    TO: "COLLECTOR"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_collector_from_umar.json"
  MAPPING5:
    FROM: "NanPlaceholder"
    TO: "PREPROCESS"
    PATH: "mapping_preprocess_from_nan.json"
  MAPPING6:
    FROM: "P_CTRL"
    TO: "PREPROCESS"
    PATH: "mapping_preprocess_from_p_ctrl.json"
  MAPPING7:
    FROM: "DATA"
    TO: "P_CTRL"
    PATH: "mapping_p_ctrl_from_data.json"
  MAPPING8:
    FROM: "UMAR"
    TO: "P_CTRL"
    PATH: "mapping_p_ctrl_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      Air_T: 24.5669