# The following are general parameters for the simulation. 
# Make sure that the RESOLUTION is the same as in your models.
OUTPUT_FOLDER_PATH: ""
START: '2020-01-01 00:00:00'
END: 12960000
RESOLUTION: 60

# The Simulators specify all the models in the simulation. Currently the following simulators are available:
#   FMU:  This will create a simulator from an FMU. 
#         PATH specifies the folder where the FMU is contained and NAME the filename.
#   TABULAR_DATA: This will create a simulator from DATA in tabular form. The supported format is hdf5.
#         PATH specifies the folder where the .h5 files are contained. The file name must correspond with the variable name of the data it containes.
#   NAN_PLACEHOLDER: This simulator will create a NaN value to all connected entities.
#         PATH specifies a file which containes all the variables you plan to connect to it.      
#   COLLECTOR: This is a simple Data collector. It will save the data of all signals you connect to it and print them after the simulation.
#         No additional information is neccessary.
SIMULATORS: 
  SIM1:
    NAME: "UMAR"
    TYPE: "FMU"
    PATH: "$DTPY$./simulators/ressources/fmu"
  SIM2:
    NAME: "PREPROCESS"
    TYPE: "FMU"
    PATH: "$DTPY$./simulators/ressources/fmu"
  SIM3:
    NAME: "DATA"
    TYPE: "TABULAR_DATA"
    PATH: "$DTPY$./simulators/ressources/data"
  SIM4:
    NAME: "NanPlaceholder"
    TYPE: "NAN_PLACEHOLDER"
    PATH: "$DTPY$./simulators/ressources/data/override_variables.json"
  SIM5:
    NAME: "COLLECTOR"
    TYPE: "COLLECTOR"
    PATH: ""

# The mappings define all the connection between the different models.
# For each pair of models that are connected you need to create a mapping and define the connected variables in a seperate file.
# See below how circular dependencies are handled.
MAPPINGS:
  MAPPING1:
    FROM: "UMAR"
    TO: "PREPROCESS"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_preprocess_from_umar.json"
    CIRCULAR_DEPENDENDY: TRUE
    INITIAL_VALUES:
      R272_Simulated_Air_Temperature: 24.5669
      R273_Simulated_Air_Temperature: 23.1496
      R274_Simulated_Air_Temperature: 23.1496
      R275_Simulated_Air_Temperature: 21.6
      R276_Simulated_Air_Temperature: 21.6
  MAPPING2:
    FROM: "PREPROCESS"
    TO: "UMAR"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_umar_from_preprocess.json"
  MAPPING3:
    FROM: "DATA"
    TO: "PREPROCESS"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_preprocess_from_data.json"
  MAPPING4:
    FROM: "PREPROCESS"
    TO: "COLLECTOR"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_collector_from_preprocess.json"
  MAPPING5:
    FROM: "NanPlaceholder"
    TO: "PREPROCESS"
    PATH: "$DTPY$./simulators/ressources/mappings/mapping_preprocess_from_nan.json"